server:
  port: 8080
spring:
  redis:
    host: 192.168.1.6
    port: 6379
    password:
    database: 0
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
    timeout: 10000
#自定义配置
redis:
  hostname: 192.168.1.6
  port: 6379

